monitor:
  ha_url: ""  # 替换为你的 HomeAssistant 地址
  ha_token: ""
  retry_times: 3                                   # 重试次数
  timeout: 10                                      # 超时时间(秒)
  schedule: "0 */5 8-23 * * *"                     # 监控时间表，支持秒级调度，此配置不支持热更新，需要重启服务
  notify:
    api_url: ""
    api_token: ""
    topic_id: 0
  tuya:
    enabled: false                                 # 是否启用涂鸦智能插座重启功能
    access_id: ""                                  # 涂鸦开发者平台 Access ID
    access_key: ""                                 # 涂鸦开发者平台 Access Key
    device_id: ""                                  # 智能插座设备 ID
    region: "cn"                                   # 区域：cn(中国), us(美国), eu(欧洲), in(印度)
    wait_seconds: 10                               # 关闭电源后等待多少秒再开启