name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 支持手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Generate config.yaml
        run: |
          cp config/config.example.yaml config/config.yaml
          sed -i "s#ha_url:.*#ha_url: \"${{ secrets.HA_URL }}\"#" config/config.yaml
          sed -i "s#ha_token:.*#ha_token: \"${{ secrets.HA_TOKEN }}\"#" config/config.yaml
          sed -i "s#api_url:.*#api_url: \"${{ secrets.NOTIFY_API_URL }}\"#" config/config.yaml
          sed -i "s#api_token:.*#api_token: \"${{ secrets.NOTIFY_API_TOKEN }}\"#" config/config.yaml
          sed -i "s#topic_id:.*#topic_id: ${{ secrets.NOTIFY_TOPIC_ID }}#" config/config.yaml

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o ha-monitor ./cmd/main.go

      - name: Deploy to server
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_TARGET: ${{ secrets.DEPLOY_TARGET }}
        run: |
          # 创建目标目录(如果不存在)
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "mkdir -p $DEPLOY_TARGET"
          
          # 复制程序和配置文件到服务器
          scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -P $DEPLOY_PORT ha-monitor config/config.yaml $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_TARGET/
          
          # 设置可执行权限
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -p $DEPLOY_PORT 
          $DEPLOY_USER@$DEPLOY_HOST "chmod +x $DEPLOY_TARGET/
          ha-monitor"

          # 复制 supervisor 配置文件并重命名
          scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -P $DEPLOY_PORT supervisor.conf $DEPLOY_USER@$DEPLOY_HOST:/tmp/ha-monitor.conf
          
          # 使用 sudo 移动配置文件到正确位置并重启服务
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "sudo mv /tmp/ha-monitor.conf /etc/supervisor/conf.d/ && \
            chmod +x $DEPLOY_TARGET/ha-monitor && \
            sudo supervisorctl update && \
            sudo supervisorctl restart ha-monitor" 